apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 3000
  externalIPs:
    - 192.168.99.102
  selector:
    io.kompose.service: app
  type: LoadBalancer
status:
  loadBalancer: {}
