version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: adnanrahic/express-docker-app
    environment:
      - LOGS_ENABLED=true
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=APP]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
    ports:
      - "80:3000"
  
  # st-logagent: 
  #   image: 'sematext/logagent:3.0.21'
  #   environment: 
  #     - LOGS_ENABLED_DEFAULT=false
  #     - LOGS_TOKEN=fbe39e0f-34b9-4ee5-981c-5e96b43599e3 
  #     - LOGS_RECEIVER_URL=https://logs-token-receiver.apps.test.sematext.com 
  #     - EVENTS_RECEIVER_URL=https://event-receiver.apps.test.sematext.com
  #   deploy:
  #     mode: global
  #   cap_add: 
  #     - SYS_ADMIN  
  #   restart: always 
  #   volumes: 
  #     - '/var/run/docker.sock:/var/run/docker.sock' 
      

  