version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: adnanrahic/express-docker-app
    deploy:
      mode: replicated
      replicas: 6
      labels: [APP=APP]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
    ports:
      - "3000:3000"
  logagent:
    image: 'sematext/logagent:latest'
    environment:
      - LOGS_TOKEN=<logs_token>
      - LOGS_RECEIVER_URL="https://logsene-receiver.sematext.com"
    cap_add:
      - SYS_ADMIN
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
